### ISSUE TITLE
Runtime errors in sim result in SUCCEEDED sim with no JSON

### ISSUE THREAD

**Issue by ghost** [zrdev/zrdev.github.io#35]

**Comment by alvarso** [comment]
From Jake:

> If the simulation fails, I don't think we're sending a message back to the
> user that indicates that it crashed.  It just says the simulation was
> successful.  Granted I was killing the simulation in a very mean way by
> depriving it of a shared lib.

**Comment by mizanul** [comment]
has been fixed with #55
