### ISSUE TITLE
Clean up filesystem on sim servers

### ISSUE THREAD

**Issue by ghost** [zrdev/zrdev.github.io#37]

**Comment by alvarso** [comment]
There were around 4 copies of libZRBackEnd_64.so on the server in various places.  I deleted them all except for the one in /usr/lib/ to be sure a spurious one wasn't being loaded, and indeed the behavior changed as soon as I did.  Be sure you know which lib is being used.  I'd recommend deploying directly to /usr/lib in an update script so you don't have to worry about paths too much.

**Comment by mizanul** [comment]
The java back-end does not load libZRBackEnd_64.so.  Java back-end has been using libZRBackEnd_64.so from /usr/lib folder.  It should not use the lib from other location. 
Anyway, I cleaned the filesystem.
