### ISSUE TITLE
Forum moderation

### ISSUE THREAD

**Issue by avivasiegel** [zrdev/zrdev.github.io#42]
We would like to be able to moderate forum posts, to remove offensive and pointless postings.

**Comment by ghost** [comment]
You can do that already. Just click the little triangle button next to
the reply button or the Actions menu at the top and select lock
thread, delete, ban author, etc. To add a new admin, go to
https://groups.google.com/a/zerorobotics.mit.edu/forum/#!managemembers/forum/members/active,
select the username, and go to Actions > Add to Role > Owner.
