### ISSUE TITLE
'Save' on Manage Teams Page not Working

### ISSUE THREAD

**Issue by rh1921** [zrdev/zrdev.github.io#50]
The Save button on the Manage Teams page isn't working (brings up a server not responding error) so you can't edit things like your team name, school, city, etc. However, you can still add members, remove members, and make members team leads.

**Comment by mizanul** [comment]
I have just did svn update build the REST service and deployed on PROD and then tested get team using REST client, I get the following error:

HTTP Status 500 - Could not write JSON: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;])</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Could not write JSON: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;])</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unknown column 'tournament0_.team_id' in 'field list' (through reference chain: edu.mit.ssl.zerorobotics.database.dao.model.TournamentsTeam[&quot;tournamentsTeammembershipCollection&quot;])
org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.writeInternal(MappingJackson2HttpMessageConverter.java:197)
org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:179)
org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:148)
org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:90)
org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:189)
org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:69)
org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:122)
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:745)

**Comment by mizanul** [comment]
I have deployed the same war file on QA and get team data works on QA.  It looks like something is not right in the DB layer on PROD

**Comment by mizanul** [comment]
Team Membership was not work on QA but working on Prod.  It looks like the touraments-teammembership table in QA has additinal columns those are needed anymore.  I have removed thos additional table and this table matches with production works on touraments-teammembership table.
Now, the Team membership works on both QA and Prod

**Comment by ghost** [comment]
Not a problem in Python implementation. Reopen this if we go back to Java
