### ISSUE TITLE
Add application page in the admin site

### ISSUE THREAD

**Issue by mizanul** [zrdev/zrdev.github.io#62]
Also, add email operation once the application is approved.

**Comment by ghost** [comment]
Also create new teams based on application information when
application is approved.

**Comment by wfeenstra** [comment]
Steps for accepting an application:
review responses 
if acceptable- change pending field to accepted
add team using data from application to team table and assign ZRHS# or use prior number
add team lead (mentor) using mentor "email" to the team membership table with team id
add team to division team table
send email to team lead (mentor) -add suggestion here

**Comment by mizanul** [comment]
Added on the admin site.
